rm(list = ls(all = TRUE))
graphics.off()
shell("cls")
data2 = read.csv(file = "C:/Users/Desktop/Quantitative final.csv")
head(data2, n=10)
install.packages("lavaan")
install.packages("OpenMx")
install.packages("semPlot")
install.packages("GGally")
install.packages("corrplot")
library(lavaan)
library(semPlot)
library(OpenMx)
library(GGally)

library(corrplot)
cor1 = cor(data2)
correlation.plot = corrplot(cor1, method = 'square')
model1 = 'DMY ~ PHT + DFW + TLP + LVP + LFL + LFW + INL + DMT + GFY + LSR'
fit1 = cfa(model1, data = data2)
summary(fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
write.table((summary(fit1, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)), file = "sumstats.txt", sep = ",", quote = FALSE, row.names = F)
path.plot = semPaths(fit1, 'std', layout = 'circle')
pdf("Path.pdf") # Create a new pdf device
print(correlation.plot)
print(path.plot)
dev.off() 
